patrick/postCreate
LikelionKau/likelion11-Songgotmae-BE pull request #1
Opened 2023-08-02 15:54 UTC by 4lazybugs

## 게시글 생성

2023-08-03 06:49 UTC, HwangBaco requested changes

2023-08-03 06:49 UTC, HwangBaco commented on src/main/java/likelion/underdog/songgotmae/web/PostController.java
> +        return postDto;
지금 Controller가 이 로직대로면 뭘 하고 있는 걸로 보이나요?

2023-08-03 06:49 UTC, HwangBaco commented on src/main/java/likelion/underdog/songgotmae/web/dao/PostDao.java
> +public class PostDao {
DAO를 알아본 것 같긴 한데, 이 DAO는 뭘 할수 있나요?

2023-08-03 06:49 UTC, HwangBaco commented on src/main/java/likelion/underdog/songgotmae/web/dto/PostDto.java
> +@AllArgsConstructor
어떤 의도로 모든 생성자를 활성화 했나요?

2023-08-03 06:49 UTC, HwangBaco commented on src/main/java/likelion/underdog/songgotmae/domain/post/PostService.java
> +        return response;
이렇게 반환한 response는 어디에 사용되나요?

그리고 postEntity를 구성할 때 Setter를 사용한 것 까진 잘 하셨습니다. 그런데 만약 setter를 안쓰고 동일한 효과를 얻으려면 어떻게 해야 할까요?

2023-08-04 05:10 UTC, 4lazybugs commented on src/main/java/likelion/underdog/songgotmae/web/PostController.java
> +        return postDto;
board/write경로에서 포스트 요청을 보내면 PostDto를 PostService에게 반환합니다

2023-08-04 05:11 UTC, 4lazybugs commented on src/main/java/likelion/underdog/songgotmae/domain/post/PostService.java
> +        return response;
Setter를 안쓰면 Data 어노테이션을 쓰면 Getter Setter어노테이션을 둘 다 포함할 수 있다고 알고 있는데 그걸 말하는 건가요??

2023-08-04 10:23 UTC, closed without merging