UD-23 feature/agreementCreate
LikelionKau/likelion11-Songgotmae-BE pull request #2
Opened 2023-08-02 20:12 UTC by Vettel22

/# 작업내용 
Agreement, 찬성을 위한 클래스에서 찬성을 생성하는 Create를 구성하는 작업.
사용자가 찬성을 누르면 누가 찬성을 했는지, 찬성사실을 저장.

/# 이슈
다수의 오류 및 사실.. 열심히 찾아보기도하고 지피티한테 이게 뭔지도 물어보며 뭔가를 생성하고 반환한다는 내용은 적었으나 이게 정말 사용자로부터 찬성을 받았는지? 그리고 받은걸 저장을 했는지? 심히 걱정이 됩니다...

2023-08-03 06:34 UTC, HwangBaco requested changes

2023-08-03 06:34 UTC, HwangBaco commented on src/main/java/likelion/underdog/songgotmae/web/AgreementController.java
> +        agreementService.submitAgreement(agreementDto);
AgreementDto.Response를 생성하지 않았는데 반환하고 있어요

2023-08-03 06:34 UTC, HwangBaco commented on src/main/java/likelion/underdog/songgotmae/web/dto/AgreementDto.java
> +        }
getter를 왜 이렇게 둔건지 잘 모르겠습니당. 공통되는 부분을 AgreementDto 에 담고, 국한되는 부분을 Create와 Response로 찣고자 한 거라면 static 처리를 한번 더 고려해보세용

2023-08-03 06:34 UTC, HwangBaco commented on src/main/java/likelion/underdog/songgotmae/domain/agreement/AgreementServiceImpl.java
> +    @Override
조회하는 것도 결국 DB에 접근은 하는거라서 Transactional로 관리해주는게 좋습니다. 다만 저번에 말한대로 `@Transactional(readOnly = true)` 와 같은 어노테이션으로 달면 더 좋겠죠

2023-08-03 06:34 UTC, HwangBaco commented on src/main/java/likelion/underdog/songgotmae/domain/agreement/AgreementService.java
> +    void submitAgreement(AgreementDto agreementDto);
이건 뭐고 위에 `void submitAgreement(...)`는 뭔가여? 오버라이드를 의도한 건가요 혹시? 서비스임플 코드에는 구현체가 없던딩

2023-08-03 06:34 UTC, HwangBaco commented on src/main/java/likelion/underdog/songgotmae/domain/agreement/Agreement.java
> +    }
굳!

2023-08-03 20:11 UTC, Vettel22 commented
수정사항: @Transactional 어노테이션 추가, Create클래스에서 static설정제거, AgreementDto.Response 생성.
변경하지 못한 것: void submitAgreement(...) , Service의 이 부분이 있어야하나요...? impl의 내용과 같은느낌.. 추상적으로(?)내용을 담아야할 Service에 어떤 내용들을 담아야 잘 담았다고 소문이 날지 잘 모르겠다.

2023-08-05 17:39 UTC, HwangBaco requested changes

2023-08-05 17:39 UTC, HwangJerry commented on src/main/java/likelion/underdog/songgotmae/domain/agreement/AgreementServiceImpl.java
> +            Member member = memberRepository.findById(agreementDto.getMemberId()).orElseThrow(() -> new IllegalArgumentException("찾을 수 없음"));
이해하고 짠 코드인지는 확실하지 않지만 예외를 깔끔하게 처리하려고 노력한 결과라고 생각이 되서 잘했다고 말씀드리고 싶습니다.

2023-08-05 17:39 UTC, HwangJerry commented on src/main/java/likelion/underdog/songgotmae/domain/agreement/AgreementServiceImpl.java
> +            agreementRepository.save(agreement);
생성자를 이해하고 있네요. 굳굳!

2023-08-05 17:39 UTC, HwangBaco commented on src/main/java/likelion/underdog/songgotmae/web/AgreementController.java
> +        agreementService.submitAgreement(agreementDto);
여전히 생성하지 않고 반환하고 있어요.

2023-08-05 17:39 UTC, HwangBaco commented on src/main/java/likelion/underdog/songgotmae/domain/agreement/AgreementService.java
> +     void submitAgreement(AgreementDto.Create agreementDto);
이 함수는 반환값이 왜 void이면 좋을지 설명할 수 있나요?

2023-08-05 17:39 UTC, HwangBaco commented on src/main/java/likelion/underdog/songgotmae/web/dto/AgreementDto.java
> +public class AgreementDto {
이 클래스를 왜 아래와 같이 구성하게 됐는지 설명할 수 있나요? static을 한건 왜 static 처리를 했는지, 안 한건 왜 안했는지, @NoArgsConstructor 어노테이션은 왜 썼는지, Create는 왜 static이 아니고, 왜 상위 클래스 필드에 대한 getter 메서드들을 Create가 가지게 되었는지 등 전부 하나하나 의도를 설명해보세요.

2023-08-05 17:39 UTC, HwangBaco commented on src/main/java/likelion/underdog/songgotmae/web/dto/AgreementDto.java
> +        }
이건 생성자를 만든 거 같은데, @Data가 어떤 역할을 하는지 잘 알고 있나요?

2023-08-07 11:40 UTC, HwangBaco approved these changes

2023-08-07 11:40 UTC, merged